CREATE TABLE IF NOT EXISTS `character_login` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`guid` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`eventTime` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
AUTO_INCREMENT=142
;
CREATE TABLE IF NOT EXISTS `furnitures_set_log` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`guid` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`eventTime` DATETIME NULL DEFAULT NULL,
	`furnituresAfter` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin'
	PRIMARY KEY (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=142
;