CREATE TABLE IF NOT EXISTS `players` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`guid` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`IMEI` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`topScore` INT(11) NULL DEFAULT NULL,
	`password` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`materialNum` INT(11) NULL DEFAULT NULL,
	`furnituresDisplayed` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`furnituresWarehouse` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`items` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_bin',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=130
;
